"""YAML Manifest catalog support for UseCaseAPI."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    ".manifest_domain.semantic.accessors": (
        "manifest_errors",
        "manifest_fields",
        "manifest_models",
        "usecase_items",
        "usecase_items_from_semantic",
    ),
    ".manifest_domain.code_first.exporter": (
        "collect_added_removed",
        "collect_changed_usecase",
        "collect_declared_set_change",
        "collect_declared_value_changes",
        "diff_manifest_with_api",
        "infer_contracts_root",
        "infer_implementations_root",
        "infer_package",
        "manifest_from_api",
        "ref_to_manifest_usecase",
    ),
    ".manifest_domain.code_first.types": (
        "collect_errors",
        "collect_models",
        "error_fields",
        "error_to_manifest",
        "field_to_manifest",
        "format_annotation",
        "format_collection_annotation",
        "format_origin_annotation",
        "model_to_manifest",
        "model_types_from_annotation",
        "validate_representable_field",
        "validate_representable_model",
    ),
    ".manifest_domain.common": (
        "_BUILTIN_TYPE_NAMES",
        "_EMPTY_SCHEMA_KEYS",
        "_GENERIC_TYPE_NAMES",
        "_JSON_SCHEMA_PRIMITIVE_TYPES",
        "_JSON_SCHEMA_STRING_FORMATS",
        "_OPENAPI_COMPONENT_KEYS",
        "_OPENAPI_JSON_CONTENT_KEYS",
        "_OPENAPI_JSON_SCHEMA_DIALECT",
        "_OPENAPI_LIFECYCLE_KEYS",
        "_OPENAPI_MEDIA_TYPE_KEYS",
        "_OPENAPI_OBJECT_MODEL_SCHEMA_KEYS",
        "_OPENAPI_OPERATION_CONTEXT_KEYS",
        "_OPENAPI_OPERATION_EXTENSION_KEYS",
        "_OPENAPI_OPERATION_KEYS",
        "_OPENAPI_OPERATION_SEMANTICS",
        "_OPENAPI_PATH_ITEM_KEYS",
        "_OPENAPI_REQUEST_BODY_KEYS",
        "_OPENAPI_RESPONSE_KEYS",
        "_OPENAPI_ROOT_EXTENSION_COMPONENT_KEYS",
        "_OPENAPI_ROOT_EXTENSION_KEYS",
        "_OPENAPI_ROOT_KEYS",
        "_OPENAPI_RUNTIME_KEYS",
        "_OPENAPI_RUNTIME_ROOT_KEYS",
        "_SCALAR_TYPE_NAMES",
        "_SCHEMA_METADATA_KEYS",
        "LEGACY_MANIFEST_KIND",
        "LEGACY_PROTOCOL_KIND",
        "MANIFEST_EXTENSION",
        "MANIFEST_KIND",
        "MANIFEST_MEDIA_TYPE",
        "MANIFEST_PROFILE_KIND",
        "OPENAPI_VERSION",
        "PROTOCOL_KIND",
        "USECASEAPI_PROFILE",
        "USECASEAPI_VERSION",
        "ContractCheckReport",
        "ManifestDiff",
        "ManifestError",
        "ManifestGuardReport",
        "ManifestScaffoldResult",
    ),
    ".manifest_domain.contract_check.report": (
        "_local_component_ref_from_string",
        "_local_component_refs",
        "_reachable_component_refs",
        "_referenced_components",
        "_referenced_error_metadata",
        "contract_check_sync_errors",
        "diff_manifests",
        "guard_manifests",
        "immutable_usecase_index",
        "normalize_contract_check_base_manifest",
        "normalize_immutable_operation",
        "render_contract_check_markdown",
        "run_contract_check",
        "sort_json_like",
    ),
    ".manifest_domain.shared.helpers": (
        "class_name",
        "default_contract_file",
        "default_implementation_class",
        "default_implementation_file",
        "default_implementation_path",
        "default_manifest_test_file",
        "default_ref_symbol",
        "ensure_init_files",
        "error_extends",
        "find_ref_symbol",
        "module_from_python_file",
        "pascal_identifier",
        "qualname",
        "required_int",
        "required_mapping",
        "required_string",
        "source_file",
        "string_list",
        "string_or_default",
        "subscript_args",
        "trim_to_root",
        "valid_contract_name",
        "valid_key",
        "valid_module_path",
        "valid_python_identifier",
        "without_none",
        "write_generated_file",
    ),
    ".manifest_domain.openapi.json_schema_types": (
        "any_of_schema_to_type_expr",
        "array_schema_to_type_expr",
        "enum_schema_to_type_expr",
        "object_schema_to_type_expr",
        "primitive_schema_to_type_expr",
        "schema_constraint_keys",
        "schema_to_type_expr",
        "string_schema_to_type_expr",
        "validate_array_schema_profile",
        "validate_object_value_schema_profile",
        "validate_schema_keys",
        "validate_schema_to_type_expr_profile",
        "validate_string_schema_profile",
    ),
    ".manifest_domain.openapi.manifest": (
        "domain_error_response",
        "openapi_components",
        "openapi_error_components",
        "openapi_manifest_from_semantic",
        "openapi_operation",
        "openapi_python_binding",
        "openapi_root_extension",
        "openapi_uses",
    ),
    ".manifest_domain.openapi.components": (
        "class_name_from_component_ref",
        "component_prefix",
        "component_schemas",
        "errors_from_components",
        "models_from_components",
        "schema_by_ref",
        "schema_to_model",
        "uses_from_extension",
        "validate_openapi_object_model_schema",
    ),
    ".manifest_domain.openapi.naming": (
        "component_name",
        "component_ref",
        "component_ref_path",
        "dependency_name",
        "error_component_name",
        "error_envelope_component_name",
        "error_payload_component_name",
        "operation_id",
        "response_component_name",
        "response_description",
        "schema_kind",
        "usecase_operation_path",
    ),
    ".manifest_domain.openapi.operation_validation": (
        "openapi_default_response_ref",
        "openapi_error_envelope_refs",
        "openapi_error_response_envelope_refs",
        "openapi_request_body_schema_ref",
        "openapi_success_response_schema_ref",
        "validate_openapi_error_envelope_enum",
        "validate_openapi_error_envelope_schema",
        "validate_openapi_json_content",
        "validate_openapi_operation_context",
        "validate_openapi_operation_contract_schemas",
        "validate_openapi_operation_error_response",
        "validate_openapi_operation_extension",
        "validate_openapi_operation_identity",
        "validate_openapi_operation_lifecycle",
        "validate_openapi_operation_semantics",
        "validate_openapi_operation_shape",
        "validate_openapi_operation_uses",
        "validate_openapi_path_item",
    ),
    ".manifest_domain.openapi.profile_validation": (
        "validate_openapi_components_shape",
        "validate_openapi_manifest",
        "validate_openapi_root_extension_shape",
        "validate_openapi_root_protocols",
        "validate_openapi_root_runtimes",
        "validate_openapi_servers",
        "validate_openapi_tags",
        "validate_semantic_manifest",
    ),
    ".manifest_domain.openapi.schema_generation": (
        "ast_arg_schema",
        "error_envelope_schema",
        "error_payload_schema",
        "field_schema",
        "literal_values",
        "model_schema",
        "primitive_type_expr_to_schema",
        "subscript_ast_to_schema",
        "type_ast_to_schema",
        "type_expr_to_schema",
    ),
    ".manifest_domain.openapi.usecase_projection": (
        "openapi_operation_declares_errors",
        "openapi_operation_to_usecase",
        "semantic_from_openapi_manifest",
        "semantic_layout",
        "source_from_python_binding",
    ),
    ".manifest_domain.scaffold.rendering": (
        "collect_type_exprs",
        "optional_contract_metadata_lines",
        "py_string_literal",
        "render_contract_binding",
        "render_error_class",
        "render_error_init_param",
        "render_model_class",
        "render_scaffold_field",
        "stdlib_import_lines",
        "tuple_expr",
        "type_expr_contains_name",
        "typing_imports",
        "usecaseapi_imports",
    ),
    ".manifest_domain.scaffold.generator": (
        "render_contract_module",
        "render_implementation_module",
        "render_manifest_graph",
        "render_manifest_markdown",
        "render_manifest_test_module",
        "render_markdown_errors",
        "render_markdown_models",
        "render_markdown_source",
        "safe_manifest_file_under_root",
        "scaffold_from_manifest",
    ),
    ".manifest_domain.semantic.catalog": (
        "error_map",
        "index_usecases",
        "model_field_changes",
        "model_map",
        "model_names_from_type_expr",
        "node_id",
        "package_name",
        "project_name",
        "project_name_from_semantic",
        "reachable_model_names",
        "semantic_manifest",
        "usecase_key",
    ),
    ".manifest_domain.semantic.validation": (
        "is_supported_literal_value",
        "is_supported_literal_value_object",
        "top_level_type_ast_allows_none",
        "type_expr_allows_none",
        "validate_contract_file_module",
        "validate_dict_generic",
        "validate_error_boundaries",
        "validate_errors",
        "validate_field",
        "validate_literal_generic",
        "validate_manifest_file_path",
        "validate_models",
        "validate_single_argument_generic",
        "validate_source",
        "validate_subscript_type_ast",
        "validate_tuple_generic",
        "validate_type_ast",
        "validate_type_expr",
        "validate_type_expr_references",
        "validate_type_references",
        "validate_usecase_identity",
        "validate_usecase_manifest",
        "validate_uses",
    ),
    ".manifest_domain.io": (
        "dump_manifest",
        "load_manifest",
        "manifest_to_yaml",
        "validate_manifest",
    ),
}

for _module_name, _names in _EXPORTS.items():
    _module = import_module(_module_name, package=__package__)
    for _name in _names:
        globals()[_name] = getattr(_module, _name)

__all__ = tuple(name for names in _EXPORTS.values() for name in names)

del import_module, _module, _module_name, _name, _names
