from __future__ import annotations

from .manifest_domain.code_first.exporter import (
    collect_added_removed as collect_added_removed,
    collect_changed_usecase as collect_changed_usecase,
    collect_declared_set_change as collect_declared_set_change,
    collect_declared_value_changes as collect_declared_value_changes,
    diff_manifest_with_api as diff_manifest_with_api,
    infer_contracts_root as infer_contracts_root,
    infer_implementations_root as infer_implementations_root,
    infer_package as infer_package,
    manifest_from_api as manifest_from_api,
    ref_to_manifest_usecase as ref_to_manifest_usecase,
)
from .manifest_domain.code_first.types import (
    collect_errors as collect_errors,
    collect_models as collect_models,
    error_fields as error_fields,
    error_to_manifest as error_to_manifest,
    field_to_manifest as field_to_manifest,
    format_annotation as format_annotation,
    format_collection_annotation as format_collection_annotation,
    format_origin_annotation as format_origin_annotation,
    model_to_manifest as model_to_manifest,
    model_types_from_annotation as model_types_from_annotation,
    validate_representable_field as validate_representable_field,
    validate_representable_model as validate_representable_model,
)
from .manifest_domain.common import (
    _BUILTIN_TYPE_NAMES as _BUILTIN_TYPE_NAMES,
    _EMPTY_SCHEMA_KEYS as _EMPTY_SCHEMA_KEYS,
    _GENERIC_TYPE_NAMES as _GENERIC_TYPE_NAMES,
    _JSON_SCHEMA_PRIMITIVE_TYPES as _JSON_SCHEMA_PRIMITIVE_TYPES,
    _JSON_SCHEMA_STRING_FORMATS as _JSON_SCHEMA_STRING_FORMATS,
    _OPENAPI_COMPONENT_KEYS as _OPENAPI_COMPONENT_KEYS,
    _OPENAPI_JSON_CONTENT_KEYS as _OPENAPI_JSON_CONTENT_KEYS,
    _OPENAPI_JSON_SCHEMA_DIALECT as _OPENAPI_JSON_SCHEMA_DIALECT,
    _OPENAPI_LIFECYCLE_KEYS as _OPENAPI_LIFECYCLE_KEYS,
    _OPENAPI_MEDIA_TYPE_KEYS as _OPENAPI_MEDIA_TYPE_KEYS,
    _OPENAPI_OBJECT_MODEL_SCHEMA_KEYS as _OPENAPI_OBJECT_MODEL_SCHEMA_KEYS,
    _OPENAPI_OPERATION_CONTEXT_KEYS as _OPENAPI_OPERATION_CONTEXT_KEYS,
    _OPENAPI_OPERATION_EXTENSION_KEYS as _OPENAPI_OPERATION_EXTENSION_KEYS,
    _OPENAPI_OPERATION_KEYS as _OPENAPI_OPERATION_KEYS,
    _OPENAPI_OPERATION_SEMANTICS as _OPENAPI_OPERATION_SEMANTICS,
    _OPENAPI_PATH_ITEM_KEYS as _OPENAPI_PATH_ITEM_KEYS,
    _OPENAPI_REQUEST_BODY_KEYS as _OPENAPI_REQUEST_BODY_KEYS,
    _OPENAPI_RESPONSE_KEYS as _OPENAPI_RESPONSE_KEYS,
    _OPENAPI_ROOT_EXTENSION_COMPONENT_KEYS as _OPENAPI_ROOT_EXTENSION_COMPONENT_KEYS,
    _OPENAPI_ROOT_EXTENSION_KEYS as _OPENAPI_ROOT_EXTENSION_KEYS,
    _OPENAPI_ROOT_KEYS as _OPENAPI_ROOT_KEYS,
    _OPENAPI_RUNTIME_KEYS as _OPENAPI_RUNTIME_KEYS,
    _OPENAPI_RUNTIME_ROOT_KEYS as _OPENAPI_RUNTIME_ROOT_KEYS,
    _SCALAR_TYPE_NAMES as _SCALAR_TYPE_NAMES,
    _SCHEMA_METADATA_KEYS as _SCHEMA_METADATA_KEYS,
    LEGACY_MANIFEST_KIND as LEGACY_MANIFEST_KIND,
    LEGACY_PROTOCOL_KIND as LEGACY_PROTOCOL_KIND,
    MANIFEST_EXTENSION as MANIFEST_EXTENSION,
    MANIFEST_KIND as MANIFEST_KIND,
    MANIFEST_MEDIA_TYPE as MANIFEST_MEDIA_TYPE,
    MANIFEST_PROFILE_KIND as MANIFEST_PROFILE_KIND,
    OPENAPI_VERSION as OPENAPI_VERSION,
    PROTOCOL_KIND as PROTOCOL_KIND,
    USECASEAPI_PROFILE as USECASEAPI_PROFILE,
    USECASEAPI_VERSION as USECASEAPI_VERSION,
    ContractCheckReport as ContractCheckReport,
    ManifestDiff as ManifestDiff,
    ManifestError as ManifestError,
    ManifestGuardReport as ManifestGuardReport,
    ManifestScaffoldResult as ManifestScaffoldResult,
)
from .manifest_domain.contract_check.report import (
    _local_component_ref_from_string as _local_component_ref_from_string,
    _local_component_refs as _local_component_refs,
    _reachable_component_refs as _reachable_component_refs,
    _referenced_components as _referenced_components,
    _referenced_error_metadata as _referenced_error_metadata,
    contract_check_sync_errors as contract_check_sync_errors,
    diff_manifests as diff_manifests,
    guard_manifests as guard_manifests,
    immutable_usecase_index as immutable_usecase_index,
    normalize_contract_check_base_manifest as normalize_contract_check_base_manifest,
    normalize_immutable_operation as normalize_immutable_operation,
    render_contract_check_markdown as render_contract_check_markdown,
    run_contract_check as run_contract_check,
    sort_json_like as sort_json_like,
)
from .manifest_domain.io import (
    dump_manifest as dump_manifest,
    load_manifest as load_manifest,
    manifest_to_yaml as manifest_to_yaml,
    validate_manifest as validate_manifest,
)
from .manifest_domain.openapi.components import (
    class_name_from_component_ref as class_name_from_component_ref,
    component_prefix as component_prefix,
    component_schemas as component_schemas,
    errors_from_components as errors_from_components,
    models_from_components as models_from_components,
    schema_by_ref as schema_by_ref,
    schema_to_model as schema_to_model,
    uses_from_extension as uses_from_extension,
    validate_openapi_object_model_schema as validate_openapi_object_model_schema,
)
from .manifest_domain.openapi.json_schema_types import (
    any_of_schema_to_type_expr as any_of_schema_to_type_expr,
    array_schema_to_type_expr as array_schema_to_type_expr,
    enum_schema_to_type_expr as enum_schema_to_type_expr,
    object_schema_to_type_expr as object_schema_to_type_expr,
    primitive_schema_to_type_expr as primitive_schema_to_type_expr,
    schema_constraint_keys as schema_constraint_keys,
    schema_to_type_expr as schema_to_type_expr,
    string_schema_to_type_expr as string_schema_to_type_expr,
    validate_array_schema_profile as validate_array_schema_profile,
    validate_object_value_schema_profile as validate_object_value_schema_profile,
    validate_schema_keys as validate_schema_keys,
    validate_schema_to_type_expr_profile as validate_schema_to_type_expr_profile,
    validate_string_schema_profile as validate_string_schema_profile,
)
from .manifest_domain.openapi.manifest import (
    domain_error_response as domain_error_response,
    openapi_components as openapi_components,
    openapi_error_components as openapi_error_components,
    openapi_manifest_from_semantic as openapi_manifest_from_semantic,
    openapi_operation as openapi_operation,
    openapi_python_binding as openapi_python_binding,
    openapi_root_extension as openapi_root_extension,
    openapi_uses as openapi_uses,
)
from .manifest_domain.openapi.naming import (
    component_name as component_name,
    component_ref as component_ref,
    component_ref_path as component_ref_path,
    dependency_name as dependency_name,
    error_component_name as error_component_name,
    error_envelope_component_name as error_envelope_component_name,
    error_payload_component_name as error_payload_component_name,
    operation_id as operation_id,
    response_component_name as response_component_name,
    response_description as response_description,
    schema_kind as schema_kind,
    usecase_operation_path as usecase_operation_path,
)
from .manifest_domain.openapi.operation_validation import (
    openapi_default_response_ref as openapi_default_response_ref,
    openapi_error_envelope_refs as openapi_error_envelope_refs,
    openapi_error_response_envelope_refs as openapi_error_response_envelope_refs,
    openapi_request_body_schema_ref as openapi_request_body_schema_ref,
    openapi_success_response_schema_ref as openapi_success_response_schema_ref,
    validate_openapi_error_envelope_enum as validate_openapi_error_envelope_enum,
    validate_openapi_error_envelope_schema as validate_openapi_error_envelope_schema,
    validate_openapi_json_content as validate_openapi_json_content,
    validate_openapi_operation_context as validate_openapi_operation_context,
    validate_openapi_operation_contract_schemas as validate_openapi_operation_contract_schemas,
    validate_openapi_operation_error_response as validate_openapi_operation_error_response,
    validate_openapi_operation_extension as validate_openapi_operation_extension,
    validate_openapi_operation_identity as validate_openapi_operation_identity,
    validate_openapi_operation_lifecycle as validate_openapi_operation_lifecycle,
    validate_openapi_operation_semantics as validate_openapi_operation_semantics,
    validate_openapi_operation_shape as validate_openapi_operation_shape,
    validate_openapi_operation_uses as validate_openapi_operation_uses,
    validate_openapi_path_item as validate_openapi_path_item,
)
from .manifest_domain.openapi.profile_validation import (
    validate_openapi_components_shape as validate_openapi_components_shape,
    validate_openapi_manifest as validate_openapi_manifest,
    validate_openapi_root_extension_shape as validate_openapi_root_extension_shape,
    validate_openapi_root_protocols as validate_openapi_root_protocols,
    validate_openapi_root_runtimes as validate_openapi_root_runtimes,
    validate_openapi_servers as validate_openapi_servers,
    validate_openapi_tags as validate_openapi_tags,
    validate_semantic_manifest as validate_semantic_manifest,
)
from .manifest_domain.openapi.schema_generation import (
    ast_arg_schema as ast_arg_schema,
    error_envelope_schema as error_envelope_schema,
    error_payload_schema as error_payload_schema,
    field_schema as field_schema,
    literal_values as literal_values,
    model_schema as model_schema,
    primitive_type_expr_to_schema as primitive_type_expr_to_schema,
    subscript_ast_to_schema as subscript_ast_to_schema,
    type_ast_to_schema as type_ast_to_schema,
    type_expr_to_schema as type_expr_to_schema,
)
from .manifest_domain.openapi.usecase_projection import (
    openapi_operation_declares_errors as openapi_operation_declares_errors,
    openapi_operation_to_usecase as openapi_operation_to_usecase,
    semantic_from_openapi_manifest as semantic_from_openapi_manifest,
    semantic_layout as semantic_layout,
    source_from_python_binding as source_from_python_binding,
)
from .manifest_domain.scaffold.generator import (
    render_contract_module as render_contract_module,
    render_implementation_module as render_implementation_module,
    render_manifest_graph as render_manifest_graph,
    render_manifest_markdown as render_manifest_markdown,
    render_manifest_test_module as render_manifest_test_module,
    render_markdown_errors as render_markdown_errors,
    render_markdown_models as render_markdown_models,
    render_markdown_source as render_markdown_source,
    safe_manifest_file_under_root as safe_manifest_file_under_root,
    scaffold_from_manifest as scaffold_from_manifest,
)
from .manifest_domain.scaffold.rendering import (
    collect_type_exprs as collect_type_exprs,
    optional_contract_metadata_lines as optional_contract_metadata_lines,
    py_string_literal as py_string_literal,
    render_contract_binding as render_contract_binding,
    render_error_class as render_error_class,
    render_error_init_param as render_error_init_param,
    render_model_class as render_model_class,
    render_scaffold_field as render_scaffold_field,
    stdlib_import_lines as stdlib_import_lines,
    tuple_expr as tuple_expr,
    type_expr_contains_name as type_expr_contains_name,
    typing_imports as typing_imports,
    usecaseapi_imports as usecaseapi_imports,
)
from .manifest_domain.semantic.accessors import (
    manifest_errors as manifest_errors,
    manifest_fields as manifest_fields,
    manifest_models as manifest_models,
    usecase_items as usecase_items,
    usecase_items_from_semantic as usecase_items_from_semantic,
)
from .manifest_domain.semantic.catalog import (
    error_map as error_map,
    index_usecases as index_usecases,
    model_field_changes as model_field_changes,
    model_map as model_map,
    model_names_from_type_expr as model_names_from_type_expr,
    node_id as node_id,
    package_name as package_name,
    project_name as project_name,
    project_name_from_semantic as project_name_from_semantic,
    reachable_model_names as reachable_model_names,
    semantic_manifest as semantic_manifest,
    usecase_key as usecase_key,
)
from .manifest_domain.semantic.validation import (
    is_supported_literal_value as is_supported_literal_value,
    is_supported_literal_value_object as is_supported_literal_value_object,
    top_level_type_ast_allows_none as top_level_type_ast_allows_none,
    type_expr_allows_none as type_expr_allows_none,
    validate_contract_file_module as validate_contract_file_module,
    validate_dict_generic as validate_dict_generic,
    validate_error_boundaries as validate_error_boundaries,
    validate_errors as validate_errors,
    validate_field as validate_field,
    validate_literal_generic as validate_literal_generic,
    validate_manifest_file_path as validate_manifest_file_path,
    validate_models as validate_models,
    validate_single_argument_generic as validate_single_argument_generic,
    validate_source as validate_source,
    validate_subscript_type_ast as validate_subscript_type_ast,
    validate_tuple_generic as validate_tuple_generic,
    validate_type_ast as validate_type_ast,
    validate_type_expr as validate_type_expr,
    validate_type_expr_references as validate_type_expr_references,
    validate_type_references as validate_type_references,
    validate_usecase_identity as validate_usecase_identity,
    validate_usecase_manifest as validate_usecase_manifest,
    validate_uses as validate_uses,
)
from .manifest_domain.shared.helpers import (
    class_name as class_name,
    default_contract_file as default_contract_file,
    default_implementation_class as default_implementation_class,
    default_implementation_file as default_implementation_file,
    default_implementation_path as default_implementation_path,
    default_manifest_test_file as default_manifest_test_file,
    default_ref_symbol as default_ref_symbol,
    ensure_init_files as ensure_init_files,
    error_extends as error_extends,
    find_ref_symbol as find_ref_symbol,
    module_from_python_file as module_from_python_file,
    pascal_identifier as pascal_identifier,
    qualname as qualname,
    required_int as required_int,
    required_mapping as required_mapping,
    required_string as required_string,
    source_file as source_file,
    string_list as string_list,
    string_or_default as string_or_default,
    subscript_args as subscript_args,
    trim_to_root as trim_to_root,
    valid_contract_name as valid_contract_name,
    valid_key as valid_key,
    valid_module_path as valid_module_path,
    valid_python_identifier as valid_python_identifier,
    without_none as without_none,
    write_generated_file as write_generated_file,
)
